#!/bin/bash

#####################################################
# This demo script is written for bash, which is 
# available on most Linux systems. However, a similar
# script could easily be written in Windows.
#####################################################

# Start the virtual machine via Vagrant
vagrant up

# Install software within the virtual machine
vagrant ssh -- ./install

# Update the Git repository within the virtual machine
vagrant ssh -- ./update_git

# Execute the analysis
vagrant ssh -- ./analyze

# Package the virtual machine in a binary file
vagrant package --output demo.box

# Stop the virtual machine
vagrant destroy -f
