#!/bin/bash

#####################################################
# This demo script is written for bash, which is 
# available on most Linux systems. However, a similar
# script could easily be written in Windows.
#####################################################

# Start the virtual machine via Vagrant
vagrant up

# Install software within the virtual machine
vagrant ssh -- ./install

# Update the Git repository within the virtual machine and execute the analysis script from PAE_Analysis
vagrant ssh -- ./update_git
vagrant ssh -- ./analyze
